export const CHANGE_COORDINATE = 'CHANGE_COORDINATE';
export const GET_WEATHER_DATA = 'GET_WEATHER_DATA';
export const NOT_FOUND = 'NOT_FOUND';
export const TOGGLE_TAB = 'TOGGLE_TAB';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
export const GET_COVID_DATA = 'GET_COVID_DATA';
export const TOGGLE_CONTENT_TAB = 'TOGGLE_CONTENT_TAB';
